server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  autoconfigure:
     exclude:
       - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
       - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
       - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    sqs:
      customer-register: ${CUSTOMER_QUEUE}

customer-bff:
  url: ${CUSTOMER_BFF_URL}
  endpoints:
    register-confirm: ${ENDPOINT_REGISTER_CONFIRM}
